### ISSUE TITLE
[Line Timetable ] timecard edit page + text block

### ISSUE THREAD

**Issue by bbonnesoeur** [CanalTP/MttBundle#64]
Page to edit line time card

*notes*
- just a page to edit a simple timecard
- you can add a text block

**Comment by vpassama** [comment]
Hi there ! 

I'm currently coding the edition page for LineTimetable and I have some technical questions. I will bring the questions one by one and I begin with the translator.

### translator

We have two different files named 'messages' and 'default' in order to translate text. In my NMM instance, when I write something like this : 
```
{{ text|trans }}
```
The file used is not 'default' but 'messages'. I would know if it is the same behavior for you or if I missed something in the configuration because it can lead to lot of little mistakes later.

Why am I asking this now ? Because I saw in the [base template](https://github.com/CanalTP/MttBundle/blob/line-timetable/Resources/views/base.html.twig) the place where you declare the pageTitle and it is coded like this : 
```
{{ pageTitle|trans }}
```

But when I look at the pageTitle value in the different controllers, it seems corresponding to keys declared in 'messages' and 'default' files so sometimes it works and sometimes it doesn't.

```
grep -r pageTitle *
Controller/StopPointController.php:                'pageTitle'         => "menu.edit_timetables",
Controller/StopTimetableController.php:                'pageTitle'             => 'stop_timetable.titles.' 
```

So, what should I do about this ? In our own bundles, we have only one file for translation and we used more keys in order to separate translations in a logical way, like this : 

```
bundle:
    menu:
        menu_object1
        menu_object2

    object:
        message:
            key1
            key2
        action:
            key1
        label:
            key1
            key2
```

Then, we don't have to think about the file where is stored the translation and we can use text|trans without the fear of breaking something. Are you interested in something similar ? We could open a dedicated PR about this if you agree. (you can see our translation file [here](
https://github.com/Tisseo/CoreBundle/blob/master/Resources/translations/messages.fr.yml))

**Comment by vpassama** [comment]
Hello @datanel :)

I saw lot of useless code in the renderLayout process for stopTimetables. Because you can't edit anymore a stopPoint (but only a stopTimetable), I will delete all the things related to stopPoint / stopPointLevel / blockLevel because they are not really used anymore.

The routes become : 

```
canal_tp_mtt_stop_timetable_edit:
    pattern: /stopTimetable/edit/networks/{externalNetworkId}/line/{externalLineId}/route/{externalRouteId}/seasons/{seasonId}

canal_tp_mtt_stop_timetable_view:
    pattern: /stopTimetable/view/networks/{externalNetworkId}/line/{externalLineId}/route/{externalRouteId}/seasons/{seasonId}/stopPoint/{externalStopPointId}
```

I need your confirmation and we could create a new PR to clean all these things.
