### ISSUE TITLE
[TESTS] Correction functional tests (crawler)

### ISSUE THREAD

**Issue by dvdn** [CanalTP/MttBundle#77]
Currently
- on master branch : OK (46 tests, 790 assertions)
- on 'feature-58-upload-line-models-and-assignation' : some fatal error :disappointed: 

Details :
```
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\BlockControllerTest::testTextBlockForm'.
    F
    ...
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\DefaultControllerTest::testNavigation'.
    E
    ...
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\FrequencyControllerTest::testEditForm'.
    F
    ...
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\LayoutModelControllerTest::testListModels'.
    F
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\LayoutModelControllerTest::testUploadGoodArchive'.
    F
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\LineControllerTest::testChoiceLayoutForm'.
    E
    ...
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testSeasonBlockDates'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testStoppointsList'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testAnonymousAccess'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testAccess'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testStopPointCodeBlock'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testStopPointPoisBlock'.
    E
    Starting test 'CanalTP\MttBundle\Tests\Functional\Controller\TimetableControllerTest::testPoiBlock'.
    E
```

@vpassama please check you have same results locally.
Starting at the NMM root.
```
cd /path/to/NMM
app/console sam:database:reset -e test_mtt && phpunit -c app/phpunit.xml --debug --verbose vendor/canaltp/mtt-bundle/Tests/Functional/Controller/
```

**Comment by vpassama** [comment]
Ok,

I can't launch the tests because I don't have a configured phpunit.xml nor a config_test_mtt.yml (I have a config_test by default but I'm not sure about its content). My phpunit.xml.dist is not configured at all.

Is this file up-to-date for testing ? https://github.com/CanalTP/Timetable/blob/master/app/phpunit.xml.dist

**Comment by dvdn** [comment]
For clarity a new branch is created 'origin/feature-58-upload-line-models-and-tests'.
Its the result of 'feature-58-upload-line-models-and-assignation' rebased on current master.

You can rebase your current work on this branch.
Phpunit.xml,dist seems ok but you need a database for test identified innmm/app/config/config_test_mtt.yml  ('-e test_mtt' of the previous command ^^): 

As example :

```
imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~

doctrine:
    dbal:
        connections:
            default:
                host:     localhost
                dbname:   nmm_test_mtt
                user:     nmm
                password: nmm
```
